#!/bin/bash
#PBS -l nodes=3:ppn=12,walltime=00:07:00
#PBS -q batch
#PBS -N videoProcessingResults
#PBS -j oe
#PBS -V

cd ~/parallelFinalProject
mpiexec -np 3 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./mW.x
